"""Implements §5 and §12: Model B Evidence Assembler with deterministic fact-validation.

ARCHITECTURE.md references:
- §3 (Deterministic vs. ML vs. LLM boundary: Model B never decides accept/contest/escalate;
  it only drafts human-readable prose within the contest path chosen upstream by decision_engine.py).
- §5 (Modeling: Model B Evidence Assembler — JSON-schema-constrained output populating
  Razorpay's real contest payload: summary + typed evidence like shipping_proof).
- §12 (Defense-only statement: Aegis never fabricates evidence. The fact-validation layer
  blocks any LLM-drafted field that doesn't match the source record rather than silently dropping it).
- §13 (Explicit guardrails against scope creep: Sandbox/test-mode only, graceful degradation).

========================================================================================
MODEL B JSON-SCHEMA CONTRACT & DESIGN SPECIFICATION (§4, §5)
========================================================================================
Model B produces a contest payload strictly conforming to Razorpay's PATCH /v1/disputes/{id}/contest
schema, matching the exact shape produced by razorpay_client.build_contest_payload_from_evidence:

{
  "summary": string,  // <-- ONLY FIELD GENERATED BY LLM (human-readable factual narrative)
  "shipping_proof": { // <-- STRUCTURED FIELDS INJECTED VERBATIM FROM EVIDENCE IN CODE
    "order_id": string,
    "dispatch_ts": integer | null,
    "delivery_ts": integer | null,
    "delivery_otp_confirmed": boolean,
    "pod_document_id": string (optional),
    "delivery_geotag": [float, float] (optional)
  },
  // OR for digital voucher fulfillment:
  "digital_delivery": {
    "order_id": string,
    "redemption_ts": integer | null,
    "fulfillment_type": "digital_voucher"
  }
}

BOUNDARY SPECIFICATION:
1. LLM-Generated Prose (Model B prompt):
   - Only `summary`: A concise, human-readable narrative summarizing the fulfillment facts.
   - Constrained by prompt_template.txt to output ONLY JSON {"summary": "..."}.
2. Structured Values Copied Verbatim (Deterministic Code):
   - `order_id`, `dispatch_ts`, `delivery_ts`, `delivery_otp_confirmed`, `pod_document_id`,
     `delivery_geotag`, `redemption_ts`.
   - These fields are NEVER regenerated by the LLM. Regenerating identifiers via an LLM call
     introduces unacceptable hallucination risk; they are copied verbatim in Python code from
     the merchant evidence store via `build_contest_payload_from_evidence`.
3. Fact-Validation Hard-Block (validate_facts.py):
   - The LLM's `summary` draft is audited before submission. If any document ID, timestamp,
     courier name, or unverified OTP assertion is present in the summary that does not match
     the source record verbatim, the draft is rejected.
   - On rejection or missing credentials, the system logs granular failure reasons and safely
     falls back to the deterministic evidence-only payload.
========================================================================================
"""

import json
import logging
import os
import re
from typing import Any, Dict, Optional, Tuple

try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv("api.env")
    load_dotenv(".env")
    load_dotenv()
except ImportError:
    pass

from src.model_b_evidence_assembler.validate_facts import validate_facts
from src.razorpay_client import build_contest_payload_from_evidence

logger = logging.getLogger("aegis.model_b")

_PROMPT_TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "prompt_template.txt")


def _load_prompt_template() -> str:
    """Load prompt template from local text file."""
    with open(_PROMPT_TEMPLATE_PATH, "r", encoding="utf-8") as f:
        return f.read()


def _resolve_credentials() -> Tuple[Optional[str], Optional[str], str]:
    """Discover LLM credentials with a deterministic, logged precedence order.

    Precedence Order:
    1. OS Environment Variables (explicit shell session overrides)
    2. .env file in workspace root
    3. api.env file in workspace root

    Returns:
        (provider, api_key, source_info): Provider ('gemini' or 'claude'), secret key, and logged source description.
    """
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    dot_env_path = os.path.join(repo_root, ".env")
    api_env_path = os.path.join(repo_root, "api.env")

    # Step 1: Check existing OS environment
    for key_var in ("GEMINI_API_KEY", "ANTHROPIC_API_KEY"):
        val = os.environ.get(key_var)
        if val:
            # Auto-detect Google key format in case key was labeled ANTHROPIC_API_KEY
            if key_var == "GEMINI_API_KEY" or val.startswith("AQ.") or val.startswith("AIzaSy") or not val.startswith("sk-ant-"):
                return "gemini", val, f"OS environment variable ({key_var})"
            return "claude", val, "OS environment variable (ANTHROPIC_API_KEY)"

    # Step 2: Check .env
    try:
        from dotenv import dotenv_values  # type: ignore
        dot_vals = dotenv_values(dot_env_path) if os.path.exists(dot_env_path) else {}
        for key_var in ("GEMINI_API_KEY", "ANTHROPIC_API_KEY"):
            val = dot_vals.get(key_var)
            if val:
                if key_var == "GEMINI_API_KEY" or val.startswith("AQ.") or val.startswith("AIzaSy") or not val.startswith("sk-ant-"):
                    return "gemini", val, f".env file ({key_var})"
                return "claude", val, ".env file (ANTHROPIC_API_KEY)"
    except ImportError:
        pass

    # Step 3: Check api.env
    try:
        from dotenv import dotenv_values  # type: ignore
        api_vals = dotenv_values(api_env_path) if os.path.exists(api_env_path) else {}
        for key_var in ("GEMINI_API_KEY", "ANTHROPIC_API_KEY"):
            val = api_vals.get(key_var)
            if val:
                if key_var == "GEMINI_API_KEY" or val.startswith("AQ.") or val.startswith("AIzaSy") or not val.startswith("sk-ant-"):
                    return "gemini", val, f"api.env file ({key_var})"
                return "claude", val, "api.env file (ANTHROPIC_API_KEY)"
    except ImportError:
        pass

    return None, None, "None (no credentials found in OS env, .env, or api.env)"


def _call_gemini_api(prompt: str, api_key: str) -> str:
    """Call Google Gemini API using google-genai SDK with verified model fallbacks."""
    from google import genai  # type: ignore
    from google.genai import types  # type: ignore

    client = genai.Client(api_key=api_key)
    preferred_model = os.environ.get("GEMINI_MODEL", "gemini-3.5-flash-lite")
    # Candidate models verified 200 OK on live API
    candidate_models = [preferred_model, "gemini-3.7-flash"]
    
    last_error = None
    for model_name in candidate_models:
        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    max_output_tokens=1024,
                ),
            )
            return response.text.strip()
        except Exception as e:
            last_error = e
            continue

    if last_error:
        raise last_error
    raise RuntimeError("No Gemini candidate models succeeded")


def _call_anthropic_api(prompt: str, api_key: str) -> str:
    """Call Anthropic API using anthropic SDK."""
    import anthropic  # type: ignore

    model_name = os.environ.get("ANTHROPIC_MODEL", "claude-3-5-sonnet-20241022")
    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.create(
        model=model_name,
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.content[0].text.strip()


def assemble_contest_payload(
    evidence: Dict[str, Any],
    human_notes: Optional[str] = None,
) -> Dict[str, Any]:
    """Assemble a rich contest payload using Model B LLM with fact-validation (§5, §12).

    Supports Google Gemini (primary: sub-second SLA latency for UDIR deadlines) and
    Anthropic Claude (fallback: deep analytical reasoning). Credentials are discovered
    via explicit logged precedence: OS env -> .env -> api.env.

    If neither credential is configured, an API error occurs, the response is malformed,
    or validate_facts rejects the draft, this function logs a warning with specific failure
    reasons and cleanly returns the deterministic fallback payload from
    `build_contest_payload_from_evidence(evidence, summary_text=human_notes)`.

    Args:
        evidence: Merchant evidence dictionary from EvidenceStore.
        human_notes: Optional notes provided by a human reviewer during escalation.

    Returns:
        Structured contest payload dictionary ready for RazorpayClient.contest_dispute.
    """
    provider, api_key, source_desc = _resolve_credentials()

    if not provider or not api_key:
        logger.warning(
            "No LLM credentials found in OS env, .env, or api.env. "
            "Gracefully degrading to deterministic evidence-fields contest payload (§12, §13)."
        )
        return build_contest_payload_from_evidence(evidence, summary_text=human_notes)

    logger.info("Model B credential resolved: Provider=%s via %s", provider.upper(), source_desc)

    # Prepare prompt
    try:
        raw_template = _load_prompt_template()
        evidence_json = json.dumps(evidence, indent=2)
        human_notes_block = (
            f"<human_notes>\n{human_notes}\n</human_notes>"
            if human_notes
            else ""
        )
        prompt = (
            raw_template
            .replace("{evidence_json}", evidence_json)
            .replace("{human_notes_block}", human_notes_block)
        )
    except Exception as e:
        logger.warning("Failed to prepare Model B prompt template: %s. Falling back.", e)
        return build_contest_payload_from_evidence(evidence, summary_text=human_notes)

    # Call LLM based on resolved provider
    try:
        if provider == "gemini":
            logger.info("Invoking Model B using Gemini API (§5)...")
            response_text = _call_gemini_api(prompt, api_key)
        else:
            logger.info("Invoking Model B using Anthropic API (§5)...")
            response_text = _call_anthropic_api(prompt, api_key)
    except Exception as e:
        logger.warning("Model B LLM API call failed: %s. Falling back to deterministic payload.", e)
        return build_contest_payload_from_evidence(evidence, summary_text=human_notes)

    # Parse JSON from response
    try:
        # Strip potential markdown fences if emitted
        clean_json = response_text
        match = re.search(r"```(?:json)?\s*(.*?)\s*```", response_text, re.DOTALL)
        if match:
            clean_json = match.group(1).strip()
        parsed = json.loads(clean_json)
        draft_summary = parsed.get("summary")
        if not draft_summary or not isinstance(draft_summary, str):
            logger.warning(
                "Model B response missing valid 'summary' string: %s. Falling back.",
                response_text,
            )
            return build_contest_payload_from_evidence(evidence, summary_text=human_notes)
    except Exception as e:
        logger.warning(
            "Failed to parse Model B JSON output: %s (raw response: %r). Falling back.",
            e,
            response_text,
        )
        return build_contest_payload_from_evidence(evidence, summary_text=human_notes)

    # Fact-validation pass (§5, §12)
    candidate_payload = {"summary": draft_summary}
    is_valid, failure_reasons = validate_facts(candidate_payload, evidence)

    if not is_valid:
        logger.warning(
            "Model B draft rejected by fact-validation hard-block layer (§12). "
            "Specific failure reasons: %s. Raw draft: %r. Falling back to deterministic payload.",
            failure_reasons,
            draft_summary,
        )
        return build_contest_payload_from_evidence(evidence, summary_text=human_notes)

    logger.info("Model B narrative passed fact-validation successfully: %s", draft_summary)
    # Inject verbatim structured fields from source evidence
    return build_contest_payload_from_evidence(evidence, summary_text=draft_summary)
